### ISSUE TITLE
1.0 change log and 1.0 source tag conflict re rowreduce

### ISSUE THREAD

**Issue by fhsm** [alimanfoo/petl#307]
The 1.0 release notes (http://petl.readthedocs.org/en/latest/changes.html?highlight=rowreduce) say that `rowreduce` is overly complicated and has been removed. The next paragraph of this document suggest using it in place of `recordreduce`.

It seems `rowreduce` is in the 1.0 source tree: https://github.com/alimanfoo/petl/blob/v1.0/petl/transform/reductions.py#L16

Perhaps the first use of `rowreduce` in the change log was supposed to be `recordreduce`?

**Comment by alimanfoo** [comment]
Hi @fhsm, thanks for this. The function `rangerowreduce` has been removed (along with the other `range...()` functions which all had complicated implementations and were hard to understand or debug). The function `rowreduce()` remains. The function `recordreduce()` was deprecated and has been removed because it was redundant. I *think* the changes section has this all correct, but let me know if you spot any inconsistencies.

**Comment by fhsm** [comment]
You're right. The highlighting makes the substring match look like a separate word 

 "rangefacet, range**rowreduce**, rangeaggregate, rangecounts, multirangeaggregate, lenstats."

**Comment by alimanfoo** [comment]
Yeah that is confusing. Anyway thanks for taking the time.

On Wednesday, 21 January 2015, fhsm <notifications@github.com> wrote:

> You're right. The highlighting makes the substring match look like a
> separate word
>
> "rangefacet, range*rowreduce*, rangeaggregate, rangecounts,
> multirangeaggregate, lenstats."
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/petl/issues/307#issuecomment-70900155>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@gmail.com
Tel: +44 (0)1865 287721
