### ISSUE TITLE
Why doesn't petl.todb method take a truncate parameter?

### ISSUE THREAD

**Issue by sunstick** [alimanfoo/petl#340]
I noticed todb method doesn't take a truncate parameter
```python
def todb(table, dbo, tablename, schema=None, commit=True,
         create=False, drop=False, constraints=True, metadata=None,
         dialect=None, sample=1000):
```
But inside the method, it calls `_todb` method which supports a truncate parameter
```python
        _todb(table, dbo, tablename, schema=schema, commit=commit,
              truncate=True)
```

Any reason that truncate is supported in `_todb` but not in `todb`?

**Comment by rogerkwoodley** [comment]
`appenddb()` handles the behavior you're talking about.  It calls the same `_todb()`, but with the `truncate=False` parameter.  

I'm thinking it's a design decision to maintain a consistent API style to the other I/O functions (e.g., `tocsv()` and `appendcsv()`, `topickle()` and `appendpickle()`, etc.).  A single function (`_todb()`) that handles everything, exposed in the API as different functions.

Personally, I prefer this approach - I'd hate to inadvertently truncate a table when I wanted to just append to it, because I forgot to set `truncate=False`.

**Comment by sunstick** [comment]
Got it. That makes a lot of sense. Thanks
