### ISSUE TITLE
search / searchcomplement don't support non-ASCII characters

### ISSUE THREAD

**Issue by cchengkiu** [alimanfoo/petl#348]
Both functions call itersearch() which applies text_type(v) on the value. We use Python 2.7 so that's equivalent to unicode(v). Is there a way to bypass the default "ASCII" encoding and use "UTF-8"?

Thanks! 
Chen

**Comment by alimanfoo** [comment]
Hi there, thanks for the report but not completely sure I understand the problem. There is a [test case](https://github.com/alimanfoo/petl/blob/master/petl/test/transform/test_regex.py#L235) for search() with unicode data that works fine, if the data are already unicode values. Could you post an example that shows how the problem arises? Thanks.

**Comment by alimanfoo** [comment]
@cchengkiu just a bump to ask if you could provide a minimal example, we're working on the 1.1 release right now so could include a fix if we can isolate the problem. Thanks.

**Comment by cchengkiu** [comment]
Hey, sorry for the delay! I was out for a while. 

I understand the issue better now. Here's one simple example (PY2):
>>> t = [["col1", "col2"],["blah", "résumé"]]
>>> petl.search(t, "col2", "blah")

gives error: 
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

I know if I pass in unicode data (u"résumé") it will work, but b/c the script reads from DB directly and doesn't convert data to unicode, it fails when there's non-ASCII characters. 

I'm wondering if there's any way to pass in a global unicode encoding setting, so that we don't need to convert the data as an intermediate step or explicitly set "encoding='utf-8'" when calling various functions (e.g. petl.tocsv)?

Thanks,
Chen

**Comment by alimanfoo** [comment]
Hi @cchengkiu, thanks for the response.

I've done some digging around and it looks like default encoding is a bit of a rats nest. 

For functions like tocsv() the default encoding is currently obtained from locale.getpreferredencoding(). This seems like a reasonable thing to do. I could possibly create a petl configuration variable, e.g., ``petl.config.default_encoding`` which if not None would be used instead of locale.getpreferredencoding(). However this would only affect IO functions like tocsv etc., it would not resolve the issue you raised.

Within itersearch() the text_type() function is used to ensure that all data values are converted to text before searching. In petl data values can be any kind of object, not just strings or numbers, and so it would not work in general to add an encoding argument to this call, because the encoding argument changes the behaviour of the unicode() built-in.

Is there any reason why you can't do something like...

```
import petl as etl
# columns 'foo' and 'bar' contain non-ascii characters
tbl = etl.fromdb(...).convert(('foo', 'bar'), lambda v: unicode(v, 'UTF-8')
tbl.search('foo', u'résumé')
```

...?

**Comment by cchengkiu** [comment]
Yes, that's what I do right now - convert before the regex search. 

Thanks for the response. Look forward to the 1.1 release! :)

**Comment by alimanfoo** [comment]
Thanks @cchengkiu. If it's OK I'll close this issue but feel free to re-open or discuss further if you would like to propose some specific changes.
