### ISSUE TITLE
Utility functions fieldnames() and dicts() don't support unicode fieldnames

### ISSUE THREAD

**Issue by sv1jsb** [alimanfoo/petl#350]
Hello,
First of all thank you very much for petl. Very useful.

I am using petl to manipulate csv files from excel.
Loading is done with the fromcsv() function.
Columns have titles with non ASCII characters and file encoding is utf-8.
Loading is done flawlessly, but when I try to get the table as a list of dicts,
with the help petl.dicts() function, I get the well known error:

    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)

I have narrowed down the problem to the base.asdicts and base.fieldnames functions which
use the str() function and not the unicode(), while iterating through the header fields.

I am using python 2.7.

Best regards,
Andreas

**Comment by alimanfoo** [comment]
Thanks Andreas, this sounds like a simple fix. I'll put this high priority for the next release, will hopefully get to that soon.

**Comment by sv1jsb** [comment]
Thanks Alistair,
I can help , if you 'd like, making a pull request.
I will only change the aforementioned lines.

**Comment by alimanfoo** [comment]
Thanks Andreas, a PR would be very welcome. I think it would be best to use
text_type() imported from petl.compat rather than unicode() as this should
work on both PY2 and PY3.

On Wednesday, December 2, 2015, Andreas Porevopoulos <
notifications@github.com> wrote:

> Thanks Alistair,
> I can help , if you 'd like, making a pull request.
> I will only change the aforementioned lines.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/petl/issues/350#issuecomment-161364144>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Tel: +44 (0)1865 287721

**Comment by sv1jsb** [comment]
Of course.
