### ISSUE TITLE
Tables created with different functions don't join properly

### ISSUE THREAD

**Issue by raspst** [alimanfoo/petl#428]
It seems that tables created from different functions don't join properly. As a simple example: 
``import petl as etl

table = [['id','color'],[1,'blue'],[2,'red'],[3,'purple']]

table2 = etl.fromcsv('test2.csv')

table = etl.fromcolumns(zip(*table[1:]),header=table[0])

join_table = etl.join(table,table2,key="id")

print(join_table)

table = etl.fromcsv('test1.csv')

join_table = etl.join(table,table2,key="id")

print(join_table)``

For the first join, I use a table constructed with fromcolumns and the other with  fromcsv, and the join returns no output. For the second join, I use fromcsv to construct both tables, using the same data as previously. For this second join, however, the expected output is produced. I have attached the test csvs below.

[test.zip](https://github.com/alimanfoo/petl/files/1228734/test.zip)

**Comment by alimanfoo** [comment]
Hi @raspst, this is probably because petl does not do any interpretation of data values when reading a CSV file, everything comes in as text, and you have to do your own conversion to dates or numbers or whatever if needed. In this case the 'id' column has Python integers in the first table, but will have strings in the second table. If you do something like 

```
table2 = etl.fromcsv('test2.csv').convert('id', int)
```

...before the join then the join should work. There is also a convertnumbers() convenience function which attempts to convert strings to numbers in all columns where possible if you don't want to manually convert each column.

Hth.

**Comment by raspst** [comment]
Hi,

Thanks for answering. Unfortunately that does not fix the issue. Even if I wrap the id values in a str() call, I get the same results as before.

**Comment by raspst** [comment]
Hi,

Thanks for the answer. It looks like that took care of the issue.
